export const authConstants = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAIL: 'SIGNUP_FAIL',
    LOGOUT: 'LOGOUT'
};

export const postConstants = {
    GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
    GET_ALL_POSTS_FAIL:'GET_ALL_POSTS_FAIL',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    GET_POST_FAIL: 'GET_POST_FAIL',
    ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
    ADD_POST_FAIL: 'ADD_POST_FAIL',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAIL: 'DELETE_POST_FAIL',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAIL: 'UPDATE_POST_FAIL'
};

export const commentConstants = {
    GET_ALL_COMMENTS_SUCCESS: 'GET_ALL_COMMENTS_SUCCESS',
    GET_ALL_COMMENTS_FAIL:'GET_ALL_COMMENTS_FAIL',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAIL: 'ADD_COMMENT_FAIL'
};